### PR TITLE
Changed return types of ceil, floor, round and (%) to return Int.

### PR DESCRIPTION
**Pull request by jutaro**
Seems obvious to me.

### CODE REVIEW

**Comment by garyb** [comment]
This has been raised a few times, but there are a few problems doing this:

- `(%)` intentionally operates on `Numbers`, as it's the only way to get modulo behaviour for non-`Int`s. You can already do this with `mod` for `Int`.
- Using `Int` for the others restricts the acceptable values they can operate on to the range of `Int32`, significantly smaller than the range of integers that `Number` can safely represent.

**Comment by garyb** [comment]
Also `0.5 % 0.7` does not produce an `Int`, so the type isn't right for that either :smile:

**Comment by paf31** [comment]
We should probably document those functions to explain the types :)

**Comment by paf31** [comment]
Maybe these belong in `-integers`?

**Comment by garyb** [comment]
Yeah, that would make sense.

**Comment by hdgarrood** [comment]
We have `floor`, `ceil`, and `round` with the types @jutaro wanted in `integers` now, so I think this can be closed.

**Pull request closed without merging**
